secret-integers/src/lib.rs
A simple fix that we should take now (instead of waiting for my ct-math branch).
=> fix comp_gte

examples/hacspec-poly1305/src/poly1305.rs, examples/hacspec-poly1305/tests/test_poly1305.rs, fstar/Hacspec.Chacha20.fst, fstar/Hacspec.Chacha20Poly1305.fst, fstar/Hacspec.Lib.fst, fstar/Hacspec.Poly1305.fst, language/src/rustspec_to_fstar.rs, lib/src/math_integers.rs, utils/abstract-integers/src/abstract_int.rs, utils/abstract-integers/src/nat_mod.rs
@franziskuskiefer can you tell me if this is better ? I changed the `poly1305.rs` to pick what you had written for HACS, but it's probably better to keep the old and more tested version that you had written earlier : this PR restore this version.
=> Fix poly impl and restored F* proofs 

Cargo.toml, examples-unsafe/Cargo.toml, examples-unsafe/benches/benchmarks.rs, utils/rc-bench/Cargo.toml, utils/rc-bench/benches/benchmarks.rs, utils/rc-bench/src/lib.rs, utils/rc-tests/Cargo.toml, utils/rc-tests/tests/aead.rs
This PR:
* adds the RustCrypto chachapoly implementation to the tests
* fixes existing benchmarks
* adds benchmarks for providers on the RustCrypto APIs
=> provider part 2

language/src/hir_to_rustspec.rs
I'm not entirely sure what changed, I don't see changes in rustc here. But this works.
=> adapt to rustc changes

.github/workflows/typecheck.yml, examples/typecheck_examples.sh, language/src/hir_to_rustspec.rs, language/src/main.rs, language/src/typechecker.rs
=> Correct alias importing

fstar/Hacspec.Lib.fst, language/language-tests/option.rs, language/language-tests/result.rs, language/src/ast_to_rustspec.rs, language/src/hir_to_rustspec.rs, language/src/name_resolution.rs, language/src/rustspec.rs, language/src/rustspec_to_easycrypt.rs, language/src/rustspec_to_fstar.rs, language/src/typechecker.rs, language/tests/Makefile, language/tests/language.rs
=> Adding Option and Result types

examples/typecheck_examples.sh, fstar/Hacspec.Chacha20.fst, fstar/Hacspec.Chacha20Poly1305.fst, fstar/Hacspec.Lib.fst, fstar/Hacspec.Poly1305.fst, fstar/Hacspec.Riot.fst, fstar/Makefile, language/language-tests/enums.rs, language/language-tests/question_mark.rs, language/src/ast_to_rustspec.rs, language/src/name_resolution.rs, language/src/rustspec.rs, language/src/rustspec_to_easycrypt.rs, language/src/rustspec_to_fstar.rs, language/src/typechecker.rs, language/tests/language.rs
=> Add support for question mark at the end of let bindings

examples-unsafe/tests/test_blake2b.rs, examples/gimli/tests/test_gimli.rs, lib/src/seq.rs, lib/tests/test_public_seq.rs, lib/tests/test_seq.rs
* implement PartialEq for (PublicSeq)
* add assert_secret_seq_eq macro
=> PartialEq update

Readme.md
=> Fix SSR18 paper link

coq/src/Bls.v, coq/src/Lib.v, examples/bls12-381/src/bls12-381.rs
Hi. I'm now a student programmer working for Bas. I was looking through a proof I wrote about the bls12-381 curve and tried to update the proof with the new coq backend. I found a small mistake in the original code for bls12-381, as well as some small mistakes and typos in the Lib.v file that Milo wrote. These should be fixed now.
=> Fix small mistakes in bls12-381 and Lib.v

coq/README.md
A little helper to get the coq opam repository.
Is this the preferred way @cmester0 or shall it be done differently?
=> Update coq readme

language/src/rustspec_to_coq.rs
Generate proof statements for exported proofs to the coq backend.
=> Added automatic test proof statement for coq when doing test passthrough

language/backend-tests/question_mark.rs, language/src/typechecker.rs, language/tests/coq/QuestionMark.v, language/tests/fstar/QuestionMark.fst
Added alias based on #210 to fix #209 #208
=> Updated typechecker

Readme.md
Adding my work to the Readme examples
=> Update Readme examples

coq/.gitignore, coq/src/Hacspec_Bls12_381.v, coq/src/Hacspec_Bls12_381_Hash.v, language/src/main.rs
An issue with checking what module is the root module resulted in some files being skipped, or rather the root module being written twice.
=> Fixed issue with root module bool

coq/src/Hacspec_Bls12_381_Hash.v, coq/src/Hacspec_Chacha20.v, coq/src/Hacspec_Chacha20poly1305.v, coq/src/Hacspec_Curve25519.v, coq/src/Hacspec_Ecdsa_P256_Sha256.v, coq/src/Hacspec_Gf128.v, coq/src/Hacspec_Hmac.v, coq/src/Hacspec_Lib.v, coq/src/Hacspec_P256.v, coq/src/Hacspec_Poly1305.v, coq/src/Hacspec_Sha256.v, coq/src/QuickChickLib.v, language/src/ast_to_rustspec.rs, language/src/name_resolution.rs, language/src/rustspec.rs, language/src/rustspec_to_coq.rs, language/src/rustspec_to_easycrypt.rs, language/src/rustspec_to_fstar.rs, language/src/typechecker.rs
Added type information to handle SeqTrait conversion without coercions. (Only implemented for Coq backend)
=> Seq array conversion explicit

language/src/main.rs, language/src/util.rs
Part of #257 , fixing some issues with version control and adding possibility to set where the _vc folder is created / read. 
- Describe the actions you performed (including buttons you clicked, text you typed, commands you ran, etc.), and describe the …
=> Fix for version control folder issue

language/Cargo.toml, language/src/main.rs
Replaced regex with glob
- Describe the actions you performed (including buttons you clicked, text you typed, commands you ran, etc.), and describe the results you observed.
By making a contribution to this project, I certify that:
(a) The contribution …
=> Replaced regex with glob

language/language-tests/result.rs, language/src/ast_to_rustspec.rs, language/src/rustspec.rs, language/src/rustspec_to_coq.rs, language/src/rustspec_to_easycrypt.rs, language/src/rustspec_to_fstar.rs, language/src/typechecker.rs
This PR allows for unannotated `Ok` and `Err` in expressions under certain conditions.
Instead of being forced to write `Result::<A, B>::Ok(a)` and `Result::<A, B>::Err(b)`, it is now allowed to write `Ok(a)` and `Err(b)` when explicit type annotation is available somewhere else.
The functions below are now valid Hacspec. The types are inferred from return types or from annotations on `let` bindings. Note that this PR doesn't remove restrictions on patterns.
```rust
fn no_annotation() -> Result<u8, u16> {
let _intermediate: Result<u8, u16> = Ok(123u8);
Err(1u16)
}
fn no_annotation_nested() -> Result<u8, u16> {
if 1 > 3 {
Err(1u16)
} else {
match Result::<u8, u16>::Ok(12u8) {
Result::<u8, u16>::Ok(x) => Err(x as u16),
Result::<u8, u16>::Err(_x) => Ok(1u8),
}
}
}
fn no_annotation_tuple() -> …
```
=> Allow unannotated `Ok` and `Err` under certain conditions

language/src/main.rs, language/src/rustspec_to_coq.rs, language/src/rustspec_to_coq_base.rs
Move #311 to hacspec repo. "Refactoring of coq backend. #317 part originating from #257."
- Describe the actions you performed (including buttons you clicked, text you typed, commands you ran, etc.), and describe the results you observed.
By making a …
=> Ssprove coq refactor

examples/aes/Cargo.toml, examples/aes128-gcm/Cargo.toml, examples/bls12-381-hash/Cargo.toml, examples/chacha20/Cargo.toml, examples/chacha20poly1305/Cargo.toml, examples/curve25519/Cargo.toml, examples/gf128/Cargo.toml, examples/p256/Cargo.toml, examples/poly1305/Cargo.toml, examples/ristretto/Cargo.toml
=> bump dependencies to fix examples build

coq_ssprove/.gitignore, coq_ssprove/README.md, coq_ssprove/_CoqProject, coq_ssprove/hacspec_coq_ssprove.opam, coq_ssprove/src/ChoiceEquality.v, coq_ssprove/src/Hacspec_Lib.v, coq_ssprove/src/Hacspec_Lib_Comparable.v, coq_ssprove/src/Hacspec_Lib_Pre.v, coq_ssprove/src/LocationUtility.v
Add coq library for SSProve backends. Part of #257 .
- Describe the actions you performed (including buttons you clicked, text you typed, commands you ran, etc.), and describe the results you observed.
By making a contribution to this project, I certify …
=> Added coq library files

coq/src/Hacspec_Lib.v, language/src/ast_to_rustspec.rs, language/src/function_dependency_resolution.rs, language/src/main.rs, language/src/name_resolution.rs, language/src/rustspec.rs, language/src/rustspec_to_coq.rs, language/src/rustspec_to_coq_base.rs, language/src/rustspec_to_coq_ssprove.rs, language/src/rustspec_to_coq_ssprove_pure.rs, language/src/rustspec_to_coq_ssprove_state.rs, language/src/rustspec_to_easycrypt.rs, language/src/rustspec_to_fstar.rs, language/src/typechecker.rs
Move #312 to hacspec repo. "Adding ssprove backends. Depends on #317 and #318 part originating from #257." (Retry of #319 , which seems to have closed automatically..)
- Describe the actions you performed (including buttons you clicked, text you typed, …
=> Add backend files

language/src/rustspec_to_fstar.rs
In general, outputting raw machine integer F* literals (eg. `8uL`) instead of math integers wrapped into machine integer coercers (eg. `pub_u64 8`) works nicely. But in the case of `u8`s, Hacl*'s `Lib.IntTypes.pub_int_t` is not able to tell apart `U8` literals from `U1` ones, thus type inference of literals gets broken everywhere in F* extractions...
This PR reverts to printing `u8` literals with `pub_u8`  (when dealing with an expression, not a pattern).
💕 Thank you!
=> F*: Insert `pub_u8` and `pub_i8` in from of `u8`/`i8` literals

fstar/Hacspec.Chacha20.Proof.fst, fstar/Hacspec.Chacha20.fst, fstar/Hacspec.Lib.FoldiLemmas.fst, fstar/Hacspec.Lib.fst, fstar/Hacspec.Poly1305.Proof.fst, fstar/Hacspec.Poly1305.fst, fstar/Makefile, fstar/_vc/Hacspec.Chacha20.fst, fstar/_vc/Hacspec.Poly1305.fst
This PR adds F* proof of equivalence between:
- [Hacspec Chacha20](https://github.com/hacspec/hacspec/blob/aa652e65b8966040ee8921a6e6351b0e86aa0b92/examples/chacha20/src/chacha20.rs) and [Hacl* Chacha20](https://github.com/hacl-star/hacl-star/blob/e1bf33064c34c5ba87a17a49611699d97d40e3fc/specs/Spec.Chacha20.fst); and
- [Hacspec Poly1305](https://github.com/hacspec/hacspec/blob/aa652e65b8966040ee8921a6e6351b0e86aa0b92/examples/chacha20/src/chacha20.rs) and [Hacl* Poly1305](https://github.com/hacl-star/hacl-star/blob/e1bf33064c34c5ba87a17a49611699d97d40e3fc/specs/Spec.Poly1305.fst).
~~This PR also adds basic F*-related CI via a Github action [`.github/workflows/generate_examples_fstar.yml`](https://github.com/W95Psp/hacspec/blob/fstar_equivalence_proofs/.github/workflows/generate_examples_fs …
=> F* equivalence proofs (Chacha20, Poly1305)

Readme.md
=> Update Readme.md. Added rsa-fdh-vrf.rs

language/src/main.rs
Changes the error message when hacspec fails to find a valid lib target. The changes are intended to:
* Remove the reference to `Cargo.toml`, since we can have lib targets not specified in it (`src/lib.rs`)
* Mention that a *lib* target is needed to avoid confusion when the package has a bin target and with the related term "compilation target"
💕 Thank you!
(I can't say that all the tests are passing because most of the integer tests are failing, with or without this change. All the other tests pass)
=> improve diagnostics for target finding

Readme.md
Refer new contributors to hacspec-v2
💕 Thank you!
=> Update readme with a deprecation warning
