hacspec/hacspec

Language.md
hacspec/src/array.rs
hacspec/src/seq.rs
hacspec/src/traits.rs
spec-examples/src/aes_gcm/aes.rs
spec-examples/src/aes_gcm/aesgcm.rs
spec-examples/src/aes_gcm/gf128.rs
spec-examples/src/blake2/blake2b.rs
spec-examples/src/chacha20_poly1305/chacha20.rs
spec-examples/src/chacha20_poly1305/chacha20poly1305.rs
spec-examples/src/chacha20_poly1305/poly1305.rs
spec-examples/src/curve25519/curve25519.rs
spec-examples/src/fips202/fips202.rs
spec-examples/src/hkdf/hkdf.rs
spec-examples/src/hmac/hmac.rs
spec-examples/src/sha2/sha2.rs
spec-examples/tests/test_aes.rs
spec-examples/tests/test_aesgcm.rs
spec-examples/tests/test_blake2b.rs
spec-examples/tests/test_chacha20.rs
spec-examples/tests/test_chacha20poly1305.rs
spec-examples/tests/test_fips202.rs
spec-examples/tests/test_gf128.rs
spec-examples/tests/test_hkdf.rs
spec-examples/tests/test_hmac.rs
spec-examples/tests/test_poly1305.rs
spec-examples/tests/test_sha2.rs

This function introduces (or rather officializes) a new feature in the hacspec language : immutable borrows for function arguments. Two advantages to this addition.
Since we can now have `msg: &ByteSeq` arguments to functions, we no longer have all the `.clone()` problems. An immutable borrow on an argument basically acts like a `const` qualifier.
By restricting the use of immutable borrows only to function arguments, `&` can be interpreted as a optional label to hacspec types and as such should not hinder too much the formalization. In terms of linear logic, applying `&` to a linear term is equivalent to promoting it to the duplicable context.

Introducing immutable borrows for function arguments

---

spec-examples/src/aes_gcm/aes.rs
spec-examples/src/aes_gcm/aesgcm.rs

With just `ByteSeq` and a `AesVariant` enum, I was able to turn the implementation of AES-GCM completely generic with respect to the 128 and 256 variants.
I'll continue with Blake2 but we can land that separately.

AES-GCM now generic

---

hacspec/src/array.rs
hacspec/src/lib.rs
hacspec/src/traits.rs
hacspec/src/transmute.rs
spec-examples/src/blake2/blake2b.rs

Thanks to the addition in the library of 
* parametric arrays ;
* various conversion functions for public and secret integers
* enhanced traits for public and secret integers
I'm able to write a generic version of Blake. Note : for now the Blake code is only suitable for Blake2b, as I was not sure what to tweak to get Blake2s right. But it should be easy to do since all the generic architecture is in place.

Added parametric arrays

---

Readme.md

All links in Examples are broken, update them to be correct.
Closes #22

Fix broken links to hacspec examples in README.md

---

Cargo.toml
hacspec-derive/Cargo.toml
hacspec-derive/src/lib.rs
hacspec-derive/tests/test_derive.rs
hacspec-dev/tests/.gitignore
hacspec/src/math_util.rs
hacspec/src/traits.rs
spec-examples/Cargo.toml
spec-examples/src/lib.rs
spec-examples/tests/.gitignore

Please see `hacspec-derive/tests/test_derive.rs` for an example of how to use the derivation system.
Operations for structs are assumed to be just field-wise operations returning in the end a whole struct. Operations like comparing are not implemented since it's unclear what would be the semantics in that case.

Deriving Numeric trait for structs and named tuples

---

examples/hacspec-chacha20/src/chacha20.rs
fstar/Hacspec.Chacha20.fst
fstar/Hacspec.Lib.fst
language/src/rustspec_to_fstar.rs
lib/src/array.rs
lib/src/seq.rs

Cosmetic changes to Chacha20 so that it matches https://tools.ietf.org/html/rfc7539#section-2.3.1. Introduced the `concat` function in the lib which could be handy elsewhere.

Improve chacha20 block to match RFC

---

language/src/ast_to_rustspec.rs
utils/provider/Cargo.toml

https://github.com/rust-lang/rust/commit/8cf35643106bba09b5d6c71ceac74dc58573f371 added `ExprKind::Underscore`. I didn't look into how it actually works but disallowed it for now.

adapt to Rust nightly changes

---

examples/riot-bootloader/src/lib.rs

I found some issues in the fletcher32 implementation:
1. both riotboot C and the fletcher32 used by the riotboot-rs C implementation use 0x0000FFFF as initial value for a checksum. The hacspec version defaulted to 0.
2. `get_chunk()` was called with the wrong argument order
3. somehow `header_as_u16_slice()` produced the wrong u16 order
The last one tripped me a bit... :smile:
With these changes (and some no_std work), this fletcher version now produces identical checksums as the one used by RIOT and https://github.com/jbangelo/fletcher.

examples/riot-bootloader: some fletcher fixes

---

.github/workflows/build_test.yml
Readme.md
language/Readme.md
language/rust-toolchain
lib/get_func_stats.sh

Pinning the Rust compiler to a version that we know is working for the typechecker.

pin Rust nightly version for typechecker

---

language/src/main.rs
language/tests/run_tests.rs

This adds all dependencies of a crate as `--extern=` to the typechecker. This makes it easier to typecheck more complex specs, especially as long as every file has to be in a different crate.

Add dependencies automatically to typechecker

---

.github/workflows/typecheck.yml
Cargo.toml
examples/curve25519/Cargo.toml
examples/ecdsa-p256-sha256/.gitignore
examples/ecdsa-p256-sha256/Cargo.toml
examples/ecdsa-p256-sha256/src/ecdsa.rs
examples/p256/src/p256.rs
examples/typecheck_examples.sh
language/Cargo.toml
language/src/hir_to_rustspec.rs
language/src/typechecker.rs
lib/src/math_integers.rs

ECDSA-P256-SHA256
There are still two typechecking errors that look like errors in the typechecker. @denismerigoux do you have an idea what could happen here?
```
error[Hacspec]: the variable r_1920 is not present in the context
--> /Users/franziskus/repos/hacspec/examples/ecdsa-p256-sha256/src/ecdsa.rs:21:15
|
21 |     let rsk = r * sk;
|               ^
error[Hacspec]: operation not available for type Scalar
--> /Users/franziskus/repos/hacspec/examples/ecdsa-p256-sha256/src/ecdsa.rs:38:14
|
38 |     let u1 = payload_hash * s_inv;
|              ^^^^^^^^^^^^^^^^^^^^
```

ecdsa p256 sha256

---

utils/attributes/Cargo.toml
utils/attributes/Readme.md
utils/attributes/src/lib.rs
utils/attributes/tests/hacspec_file.rs

This adds the attribute for #104.
Note that this PR does not handle tha attribute in the compiler yet.

hacspec_unsafe attribute

---

.github/workflows/build_test.yml
.github/workflows/typecheck.yml
fstar/Hacspec.Chacha20.fst
fstar/Hacspec.Lib.fst
fstar/Hacspec.Poly1305.fst
fstar/Hacspec.Riot.fst
language/language-tests/question_mark.rs
language/src/ast_to_rustspec.rs
language/src/name_resolution.rs
language/src/rustspec.rs
language/src/rustspec_to_easycrypt.rs
language/src/rustspec_to_fstar.rs
language/src/typechecker.rs

Allow question marks at the end of reassignments and array updates

---

lib/src/seq.rs
lib/src/traits.rs

Elements in a `Seq` had to be `Copy` for some reason. This is not necessary and is being removed here.

Drop Copy requirement for Seq

---

lib/src/seq.rs

Right now in order to append an element to a sequence it is necessary to create a new temporary sequence and then concatenate the two sequences. This is cumbersome and unnecessary. Instead `Seq` needs to get a function `pub fn push(&self, next: &T) -> Self` and `pub fn push_owned(mut self, mut next: T) -> Self`.
These need adding to the F* and Coq libraries.

Add push function to Seq

---

coq/src/Bls.v
examples/bls12-381/src/bls12-381.rs

I've removed the recursive function most_significant_bit from bls12-381.rs as I found out that recursive functions are not allowed in hacspec. 
This also fixes an issue where multiplying a curve point p with zero would give p instead of the point at infinity.

Remove recursive function from bls12-381

---

language/Cargo.toml
language/src/bin.rs
language/src/main.rs
language/src/util.rs

A first batch of basic typechecker usability improvements.
- support [--manifest-path argument](https://doc.rust-lang.org/cargo/commands/cargo-build.html#manifest-options)
- don't require crate name if only one crate is available
- slightly better errors
- support crates that specify the [crate-type](https://doc.rust-lang.org/cargo/reference/cargo-targets.html)

improve typechecker usability

---

.github/workflows/build_test.yml
.github/workflows/examples.yml
language/src/rustspec_to_fstar.rs

The main purpose of this PR is to make the CI faster by running the example tests only in release mode.
But I also slipped in the `uppercase_first_letter` function to force upper case in F* for now. @denismerigoux let me know if you're happy with this. I know it's not ideal and we should make this nicer. But this way we don't break the generated F* code all the time (in this way).

Run only release tests on examples

---

language/Cargo.toml

Seems like "im" version  15.1.0 broke something. See #247 and #72.
This PR pins "im" to 15.0.x.

language: pin "im" dependency to 15.0.x

---

Cargo.toml

The old resolver doesn't allow testing with `--no-default-features`, e.g., doing
cargo build --target thumbv7em-none-eabi -p hacspec-lib --no-default-features --features alloc
See #72.
This PR sets the workspace resolver to "2".

set `resolver = "2"` in workspace Cargo.toml

---

.github/workflows/build_test.yml
Cargo.toml
lib/Cargo.toml
lib/src/array.rs
lib/src/lib.rs
lib/src/machine_integers.rs
lib/src/math_util/ct_poly.rs
lib/src/prelude.rs
lib/src/seq.rs
lib/src/traits.rs
lib/src/util.rs
lib/src/vec_util.rs
utils/abstract-integers/Cargo.toml
utils/abstract-integers/src/abstract_int.rs
utils/abstract-integers/src/lib.rs
utils/abstract-integers/src/nat_mod.rs
utils/secret-integers/src/lib.rs

Here's my work in progress branch to build with no_std (but still using alloc).
This mainly:
1. converts uses of `std::*` to `core::*` and `alloc::*` where possible
2. sets up features for std (as default) and no_std/alloc when std is not used
~~3. adds `examples/no_std`, which is a Cortex-M bare-metal application that can run in QEMU~~
~~4. adds a github workflow that runs `examples/no_std` in QEMU~~ (split out to follow-up)
~~This is work in progress, but I'd like to see what your CI thinks. :)~~
Update April '22:
- I gave this another look and rebased it to current master
- running the tests locally works fine
- `examples/no_std` builds (and imports hacspec-lib), but doesn't actually use any of it. We can do that later.
Update May 3rd:
- split out example and CI workflow

initial no_std work

---

language/Cargo.toml
language/language-tests/enums.rs
language/src/ast_to_rustspec.rs
language/src/main.rs
language/src/name_resolution.rs
language/src/rustspec.rs
language/src/typechecker.rs

This allows us updating `im`.
I didn't update all `union` calls. But we probably should. Or maybe we should drop `im` and use the `std::collections` instead.
Also see https://github.com/bodil/im-rs/issues/202

fix im union

---

examples/sha256/src/sha256.rs

I'm working with [crux-mir-comp](https://github.com/GaloisInc/saw-script/tree/master/crux-mir-comp) to verify an implementation against specs in this repository. Some of the functions in this repository need to be public for that purpose.
This PR makes several hacspec functions for the sha256 example `pub` so crux can access them.

[examples/sha256] make a few sha256 spec functions public

---

examples/bls12-381-hash/Cargo.toml

Newer versions of the repo use a relative git submodule that breaks our builds.

pin concordium-base dependency to a50612e0

---

language/src/hir_to_rustspec.rs
language/test-crate/src/submod1/another_submod1_file.rs
language/test-crate/src/submod2/mod.rs

Hi,
This PR should fix #272.
While looking for external symbols from a local module, the case `ItemKind::Const` was missed, and function `process_fn_id` was expecting paths of identifiers of length exactly one.

Make constants from other modules visible (fixes #272)

---

language/language-tests/tuples.rs
language/src/ast_to_rustspec.rs

As @cmester0 described in #287, a struct with an empty tuple used to result in a panic in module `ast_to_rustspec`.
For example, the following snippet was problematic:
```rust
pub struct EmptyTuple();
pub fn test_empty_tuple() -> EmptyTuple {
EmptyTuple()
}
```
This PR just reformulates two `unwrap`s into pattern matching and adds a test case.

Support struct whose payload is `()` (fixes #287)

---

language/language-tests/tuples.rs
language/src/ast_to_rustspec.rs
language/src/rustspec.rs
language/src/rustspec_to_coq.rs
language/src/rustspec_to_easycrypt.rs
language/src/rustspec_to_fstar.rs
language/src/typechecker.rs

Hi,
As per issue #187, Hacspec used to treat `unit` and `()` as two different types, causing e.g. issue #228.
This PR thus drops the constructor `BaseTyp::Unit`, in favor of `BaseTyp::Tuple(!vec[])`.

Drop base type `Unit` in favor of empty tuple (Fixes #228 and #187)

---

fstar/Hacspec.Lib.fst
language/language-tests/question_mark.rs
language/src/ast_to_rustspec.rs
language/src/elab_monadic_lets.rs
language/src/main.rs
language/src/name_resolution.rs
language/src/rustspec.rs
language/src/rustspec_to_coq.rs
language/src/rustspec_to_easycrypt.rs
language/src/rustspec_to_fstar.rs
language/src/typechecker.rs

Hi,
This PR allows question marks to appear anywhere in (most of) expressions, e.g., `f(x?) + g(y?)?`.
To do so, this PR adds the following nodes in the `Expression` enum:
- `QuestionMark`, which simply reflects syntactically the presence of a question mark in an expression;
- `MonadicLet`, which are elaborated from expressions containing `QuestionMark`, transforming and hoisting `QuestionMark`s in monadic bindings.
For now, there is some duplication between the code introduced by this PR and the existing code that handles question marks on statements. Also, "monadic" expressions are hoisted from the left to the right (e.g. `x.f y` with `x` and `y` monadic is elaborated to `x >>= (fun mx -> y >>= (fun my -> mx.f my)`): empirically that seems to match what Rust does, but I haven't found …

Allow question marks within expressions

---

language/language-tests/literals.rs
language/language-tests/result.rs
language/src/ast_to_rustspec.rs
language/src/rustspec.rs
language/src/rustspec_to_coq.rs
language/src/rustspec_to_easycrypt.rs
language/src/rustspec_to_fstar.rs
language/src/typechecker.rs
language/tests/0_language.rs

Hacspec used to treat every unannotated integer literal (e.g. `42`, an integer without a suffix like `u8` or `i64`) as a `usize` integer.
This PR adds a new literal variant to Hacspec AST, `UnannotatedInt`, and every unannotated integer literal is interpreted as a `UnannotatedInt`.
Those are then concretized at typechecking.
This PR adds the test `positive_literals`.
This PR depends on #315 and #322.
- [ x What process did you follow to verify that your change has the desired effects?
- What are the possible side-effects or negative …

Allow unannotated integer literals 

---

language/language-tests/enums.rs
language/src/ast_to_rustspec.rs
language/src/elab_monadic_lets.rs
language/src/main.rs
language/src/name_resolution.rs
language/src/rustspec.rs
language/src/rustspec_to_coq.rs
language/src/rustspec_to_easycrypt.rs
language/src/rustspec_to_fstar.rs
language/src/typechecker.rs

This PR brings support for field accessors on tuples and tuple structs, one can now write `(x, y, z).2` or `Foo(x, y).0` (when `Foo` is a [tuple struct](https://doc.rust-lang.org/book/ch05-01-defining-structs.html#using-tuple-structs-without-named-fields-to-create-different-types)).
- How did you verify that the change has not …

Support field accessors on tuples and tuple structs

---

lib/src/array.rs
lib/src/lib.rs
lib/src/math_integers.rs
lib/src/prelude.rs
lib/src/traits.rs

`use hacspec_lib::prelude::*;` isn't valid hacspec. Replacing its occurences in documentation with `use hacspec_lib::*;` since `hacspec-lib` reexports the prelude anyways.
I've ran the doctests and they all pass after this change.
💕 Thank you!
(I can't say that all the tests are passing because most of the integer tests are failing, with or without this change. All the other tests pass)

`use hacspec_lib::prelude::*;` -> `use hacspec_lib::*;`

---

lib/src/machine_integers.rs
rust-toolchain

Hax tests depend on Hacspec libs because those include the specs from https://github.com/hacspec/specs/, and most of them are still using Hacspec lib
The library appears to be broken, thus here is a minimal fix that makes the library and the specs repo compile again.

Fix a bug in the macros of hacspec lib
